#!/bin/bash

DIR=/home/james/Downloads/tmp/$(date +%Y_%m_%d)

mkdir -p  $DIR
cd $DIR
/home/james/bin/motherless.sh http://motherless.com/live
/home/james/bin/motherless.sh http://motherless.com/videos/all/favorited
/home/james/bin/motherless.sh http://motherless.com/videos/all/viewed
cd ..
/home/james/bin/sendtopole $DIR
