#!/bin/bash

DBDIR_MAC=/home/james/Dropbox/xfer/home_mac
DBDIR_LINUX=/home/james/Dropbox/xfer/home_linux

DLDIR=/home/james/Downloads/frompole

FLIST=$(ls ${DBDIR_MAC}/*/filelist.*.dl ${DBDIR_LINUX}/*/filelist.*.dl 2>/dev/null)

for FNAME in ${FLIST}
do
  DATADIR=$(dirname ${FNAME})
  WORKINGDIR=${DLDIR}/$(basename ${DATADIR})
  DLFILE=$(basename ${FNAME})

  cd ${DATADIR}
  /usr/bin/sha512sum --status -c ${FNAME}
  if (( $? == 0 ))
  then
    SPLITFIRST=$(head -n 1 ${DLFILE} |awk '{print $2}')
    SPLITBASE=${SPLITFIRST%_*}
    BASENAME=${SPLITFIRST%%.*}
    TGZFILE=${BASENAME}.tar.gz
    mv ${DATADIR} ${DLDIR}
    cd ${WORKINGDIR}
    cat ${SPLITBASE}_* > $TGZFILE
    mkdir ${BASENAME}
    mkdir ${BASENAME}/split
    mv ${SPLITBASE}_* ${BASENAME}/split
    mv ${TGZFILE} ${BASENAME}
    cd ${BASENAME}
    tar -xzf ${TGZFILE}
    rm ${TGZFILE}
    if [[ -f ftp.dl ]]
    then
      mv ftp.dl ..
    fi
  fi
done
