#!/usr/bin/env python

#############################################################################
# File name: randword
# Author: James Casey
# Date created: 2015-11-17
# Date last modified: 2015-11-17
# Description: A quick and dirty random word generator.
#############################################################################

__author__ = "James Casey"
__copyright__ = "Copyright 2015"
__credits__ = ["James Casey"]
__license__ = "GPL"
__version__ = "0.1"
__maintainer__ = "James Casey"
__email__ = "hanavi@gmail.com"
__status__ = "Production"

from numpy.random import randint
from numpy import array
import sys

# Load words from wordlist
fname = "/usr/share/dict/words"
words = array(open(fname).readlines())

# Get word count
count = int(sys.argv[1]) if len(sys.argv) == 2 else 5

# Print out words
print(" ".join([word.strip() for word in words[randint(0,len(words),count)]]))
